Final_Project: Core/Src/capsulas.c File Reference
capsulas.c File Reference
#include "capsulas.h"
Functions
Receita lerSensorCapsulas ()
Le o sensor de capsulas.
int capsulaInserida (Receita CAPSULA)
Exibe tela de inicio de preparo.
void iniciarPreparo (Receita CAPSULA)
Inicia o preparo passando a receita da capsula.
Variables
Receita CAPSULA_nao_inserida = {SEM_CAPSULA, SEM_AGUA, "", 0, 0, 0}
Receita CAPSULA_agua = {CAPSULA_AGUA, SEM_AGUA, "Escolha a agua", 0, 3.0, 0}
Receita CAPSULA_agua_com_gas = {CAPSULA_AGUA_COM_GAS, AGUA_GELADA, "Agua com gas", 15, 3.0, 1.5}
Receita CAPSULA_cha_gelado = {CAPSULA_CHA_GELADO, AGUA_GELADA, "Cha gelado", 15, 2.7, 0}
Receita CAPSULA_cha_quente = {CAPSULA_CHA_QUENTE, AGUA_QUENTE, "Cha Quente", 60, 2.7, 0}
Receita CAPSULA_refrigerante = {CAPSULA_REFRIGERANTE, AGUA_GELADA, "Refrigerante", 17, 4.0, 2.56}
Function Documentation
capsulaInserida()
int capsulaInserida (Receita CAPSULA)
Exibe tela de inicio de preparo.
Return values
1 quando o preparo foi terminado
0 quando o preparo nao foi terminado
Definition at line 62 of file capsulas.c.
References AGUA_GELADA, AGUA_NATURAL, AGUA_QUENTE, CAPSULA_AGUA, heartBeat(), iniciarPreparo(), lcd_clear(), lcd_set_cursor(), lcd_write_string(), ler_teclado(), Receita::nomeCapsula, Receita::temperaturaAgua, Receita::tipoAgua, and Receita::tipoCapsula.
iniciarPreparo()
void iniciarPreparo (Receita CAPSULA)
Inicia o preparo passando a receita da capsula.
Return values
Capsula precisa de CO2
Definition at line 187 of file capsulas.c.
References AGUA_GELADA, AGUA_NATURAL, AGUA_QUENTE, coolerPID(), HAL_Delay(), HAL_GetTick(), HAL_GPIO_ReadPin(), HAL_GPIO_WritePin(), heartBeat(), heaterPID(), lcd_clear(), lcd_set_cursor(), lcd_write_string(), P1_PIN, P1_PORT, P2_PIN, P2_PORT, pwmBomba(), Receita::temperaturaAgua, Receita::tempoAgua, Receita::tempoCO2, Receita::tipoAgua, Y1_PIN, Y1_PORT, Y2_PIN, Y2_PORT, Y3_PIN, Y3_PORT, Y4_PIN, and Y4_PORT.
Referenced by capsulaInserida().
lerSensorCapsulas()
Receita lerSensorCapsulas (void)
Le o sensor de capsulas.
Return values
retorna a receita equivalente aos pinos
Definition at line 21 of file capsulas.c.
References CAPSULA_agua, CAPSULA_agua_com_gas, CAPSULA_BIT_0, CAPSULA_BIT_0_PORT, CAPSULA_BIT_1, CAPSULA_BIT_1_PORT, CAPSULA_BIT_2, CAPSULA_BIT_2_PORT, CAPSULA_cha_gelado, CAPSULA_cha_quente, CAPSULA_nao_inserida, CAPSULA_refrigerante, and HAL_GPIO_ReadPin().
Variable Documentation
CAPSULA_agua
Receita CAPSULA_agua = {CAPSULA_AGUA, SEM_AGUA, "Escolha a agua", 0, 3.0, 0}
Definition at line 10 of file capsulas.c.
Referenced by lerSensorCapsulas().
CAPSULA_agua_com_gas
Receita CAPSULA_agua_com_gas = {CAPSULA_AGUA_COM_GAS, AGUA_GELADA, "Agua com gas", 15, 3.0, 1.5}
Definition at line 11 of file capsulas.c.
Referenced by lerSensorCapsulas().
CAPSULA_cha_gelado
Receita CAPSULA_cha_gelado = {CAPSULA_CHA_GELADO, AGUA_GELADA, "Cha gelado", 15, 2.7, 0}
Definition at line 12 of file capsulas.c.
Referenced by lerSensorCapsulas().
CAPSULA_cha_quente
Receita CAPSULA_cha_quente = {CAPSULA_CHA_QUENTE, AGUA_QUENTE, "Cha Quente", 60, 2.7, 0}
Definition at line 13 of file capsulas.c.
Referenced by lerSensorCapsulas().
CAPSULA_nao_inserida
Receita CAPSULA_nao_inserida = {SEM_CAPSULA, SEM_AGUA, "", 0, 0, 0}
Definition at line 9 of file capsulas.c.
Referenced by lerSensorCapsulas().
CAPSULA_refrigerante
Receita CAPSULA_refrigerante = {CAPSULA_REFRIGERANTE, AGUA_GELADA, "Refrigerante", 17, 4.0, 2.56}
Definition at line 14 of file capsulas.c.
Referenced by lerSensorCapsulas().