Final_Project: Core/Inc/capsulas.h File Reference
capsulas.h File Reference
#include "stm32f1xx_hal.h"
#include "heartBeat.h"
#include "lcd16x2.h"
#include "teclado.h"
#include "PWM.h"
#include <stdio.h>
Data Structures
struct Receita
Macros
#define Y1_PORT GPIOB
#define Y1_PIN GPIO_PIN_9
#define Y2_PORT GPIOB
#define Y2_PIN GPIO_PIN_8
#define Y3_PORT GPIOB
#define Y3_PIN GPIO_PIN_7
#define Y4_PORT GPIOB
#define Y4_PIN GPIO_PIN_6
#define CAPSULA_BIT_0_PORT GPIOA
#define CAPSULA_BIT_0 GPIO_PIN_8
#define CAPSULA_BIT_1_PORT GPIOB
#define CAPSULA_BIT_1 GPIO_PIN_15
#define CAPSULA_BIT_2_PORT GPIOB
#define CAPSULA_BIT_2 GPIO_PIN_14
#define P1_PORT GPIOC
#define P1_PIN GPIO_PIN_14
#define P2_PORT GPIOC
#define P2_PIN GPIO_PIN_15
Enumerations
enum Tipo_CAPSULA {
SEM_CAPSULA, CAPSULA_AGUA, CAPSULA_AGUA_COM_GAS, CAPSULA_CHA_GELADO,
CAPSULA_CHA_QUENTE, CAPSULA_REFRIGERANTE
}
enum Tipo_AGUA { SEM_AGUA, AGUA_GELADA, AGUA_QUENTE, AGUA_NATURAL }
Functions
void iniciarPreparo (Receita CAPSULA)
Inicia o preparo passando a receita da capsula.
void heaterPID (int setPoint)
Controlador PID de aquecimento.
void coolerPID (int setPoint)
Controlador PID de resfriamento.
Receita lerSensorCapsulas (void)
Le o sensor de capsulas.
int capsulaInserida (Receita tipoCapsula)
Exibe tela de inicio de preparo.
Macro Definition Documentation
CAPSULA_BIT_0
#define CAPSULA_BIT_0 GPIO_PIN_8
Definition at line 31 of file capsulas.h.
CAPSULA_BIT_0_PORT
#define CAPSULA_BIT_0_PORT GPIOA
Definition at line 30 of file capsulas.h.
CAPSULA_BIT_1
#define CAPSULA_BIT_1 GPIO_PIN_15
Definition at line 34 of file capsulas.h.
CAPSULA_BIT_1_PORT
#define CAPSULA_BIT_1_PORT GPIOB
Definition at line 33 of file capsulas.h.
CAPSULA_BIT_2
#define CAPSULA_BIT_2 GPIO_PIN_14
Definition at line 37 of file capsulas.h.
CAPSULA_BIT_2_PORT
#define CAPSULA_BIT_2_PORT GPIOB
Definition at line 36 of file capsulas.h.
P1_PIN
#define P1_PIN GPIO_PIN_14
Definition at line 40 of file capsulas.h.
P1_PORT
#define P1_PORT GPIOC
Definition at line 39 of file capsulas.h.
P2_PIN
#define P2_PIN GPIO_PIN_15
Definition at line 43 of file capsulas.h.
P2_PORT
#define P2_PORT GPIOC
Definition at line 42 of file capsulas.h.
Y1_PIN
#define Y1_PIN GPIO_PIN_9
Definition at line 19 of file capsulas.h.
Y1_PORT
#define Y1_PORT GPIOB
Definition at line 18 of file capsulas.h.
Y2_PIN
#define Y2_PIN GPIO_PIN_8
Definition at line 22 of file capsulas.h.
Y2_PORT
#define Y2_PORT GPIOB
Definition at line 21 of file capsulas.h.
Y3_PIN
#define Y3_PIN GPIO_PIN_7
Definition at line 25 of file capsulas.h.
Y3_PORT
#define Y3_PORT GPIOB
Definition at line 24 of file capsulas.h.
Y4_PIN
#define Y4_PIN GPIO_PIN_6
Definition at line 28 of file capsulas.h.
Y4_PORT
#define Y4_PORT GPIOB
Definition at line 27 of file capsulas.h.
Enumeration Type Documentation
Tipo_AGUA
enum Tipo_AGUA
Enumerator
SEM_AGUA
AGUA_GELADA
AGUA_QUENTE
AGUA_NATURAL
Definition at line 46 of file capsulas.h.
Tipo_CAPSULA
enum Tipo_CAPSULA
Enumerator
SEM_CAPSULA
CAPSULA_AGUA
CAPSULA_AGUA_COM_GAS
CAPSULA_CHA_GELADO
CAPSULA_CHA_QUENTE
CAPSULA_REFRIGERANTE
Definition at line 45 of file capsulas.h.
Function Documentation
capsulaInserida()
int capsulaInserida (Receita CAPSULA)
Exibe tela de inicio de preparo.
Return values
1 quando o preparo foi terminado
0 quando o preparo nao foi terminado
Definition at line 62 of file capsulas.c.
References AGUA_GELADA, AGUA_NATURAL, AGUA_QUENTE, CAPSULA_AGUA, heartBeat(), iniciarPreparo(), lcd_clear(), lcd_set_cursor(), lcd_write_string(), ler_teclado(), Receita::nomeCapsula, Receita::temperaturaAgua, Receita::tipoAgua, and Receita::tipoCapsula.
coolerPID()
void coolerPID (int setPoint)
Controlador PID de resfriamento.
Return values
Definition at line 538 of file main.c.
References adcAvgData, adcAvgDataT2, adcData, contAmostras, hadc1, HAL_ADC_Start_DMA(), HAL_ADC_Start_IT(), heartBeat(), lcd_clear(), lcd_set_cursor(), lcd_write_string(), NUMBER_OF_CONVERSION, NUMBER_OF_SAMPLES, T1, T2, and TIM2.
Referenced by iniciarPreparo().
heaterPID()
void heaterPID (int setPoint)
Controlador PID de aquecimento.
Return values
Definition at line 495 of file main.c.
References adcAvgData, adcAvgDataT2, adcData, contAmostras, hadc1, HAL_ADC_Start_DMA(), HAL_ADC_Start_IT(), heartBeat(), lcd_clear(), lcd_set_cursor(), lcd_write_string(), NUMBER_OF_CONVERSION, NUMBER_OF_SAMPLES, T1, T2, and TIM2.
Referenced by iniciarPreparo().
iniciarPreparo()
void iniciarPreparo (Receita CAPSULA)
Inicia o preparo passando a receita da capsula.
Return values
Capsula precisa de CO2
Definition at line 187 of file capsulas.c.
References AGUA_GELADA, AGUA_NATURAL, AGUA_QUENTE, coolerPID(), HAL_Delay(), HAL_GetTick(), HAL_GPIO_ReadPin(), HAL_GPIO_WritePin(), heartBeat(), heaterPID(), lcd_clear(), lcd_set_cursor(), lcd_write_string(), P1_PIN, P1_PORT, P2_PIN, P2_PORT, pwmBomba(), Receita::temperaturaAgua, Receita::tempoAgua, Receita::tempoCO2, Receita::tipoAgua, Y1_PIN, Y1_PORT, Y2_PIN, Y2_PORT, Y3_PIN, Y3_PORT, Y4_PIN, and Y4_PORT.
Referenced by capsulaInserida().
lerSensorCapsulas()
Receita lerSensorCapsulas (void)
Le o sensor de capsulas.
Return values
retorna a receita equivalente aos pinos
Definition at line 21 of file capsulas.c.
References CAPSULA_agua, CAPSULA_agua_com_gas, CAPSULA_BIT_0, CAPSULA_BIT_0_PORT, CAPSULA_BIT_1, CAPSULA_BIT_1_PORT, CAPSULA_BIT_2, CAPSULA_BIT_2_PORT, CAPSULA_cha_gelado, CAPSULA_cha_quente, CAPSULA_nao_inserida, CAPSULA_refrigerante, and HAL_GPIO_ReadPin().