Final_Project: Core/Src/lcd16x2.c File Reference
lcd16x2.c File Reference
#include "lcd16x2.h"
Macros
#define RS GPIO_PIN_15
#define EN GPIO_PIN_3
#define D4 GPIO_PIN_9
#define D5 GPIO_PIN_10
#define D6 GPIO_PIN_11
#define D7 GPIO_PIN_12
#define LCD_GPIO_Port GPIOA
#define LCD_GPIO_Port_EN GPIOB
Functions
void lcd_write_data (char data)
Escreve um caracter no display.
void lcd_write_int (int data)
Mostra no display uma variavel do tipo inteiro.
void lcd_write_command (char cmd)
Envia um camando para o display.
void lcd_set_cursor (char row, char col)
Posiciona o cursor do display.
void lcd_write_command_init (char cmd)
Funcao usada para inicializar o display.
void lcd_init (void)
Inicia o display.
void lcd_clear (void)
Limpa o display.
void lcd_write_string (char *str)
Escreve uma String no display.
Variables
uint8_t character1 [8] = { 0x02, 0x04, 0x0E, 0x01, 0x0F, 0x11, 0x0F, 0x00 }
uint8_t character2 [8] = { 0x02, 0x04, 0x0E, 0x11, 0x1F, 0x10, 0x0E, 0x00 }
uint8_t character3 [8] = { 0x00, 0x0E, 0x10, 0x10, 0x11, 0x0E, 0x04, 0x00 }
uint8_t character4 [8] = { 0x1F, 0x00, 0x0E, 0x01, 0x0F, 0x11, 0x0F, 0x00 }
uint8_t character5 [8] = { 0x1F, 0x00, 0x0E, 0x11, 0x11, 0x11, 0x0E, 0x00 }
Macro Definition Documentation
D4
#define D4 GPIO_PIN_9
Definition at line 12 of file lcd16x2.c.
D5
#define D5 GPIO_PIN_10
Definition at line 13 of file lcd16x2.c.
D6
#define D6 GPIO_PIN_11
Definition at line 14 of file lcd16x2.c.
D7
#define D7 GPIO_PIN_12
Definition at line 15 of file lcd16x2.c.
EN
#define EN GPIO_PIN_3
Definition at line 11 of file lcd16x2.c.
LCD_GPIO_Port
#define LCD_GPIO_Port GPIOA
Definition at line 16 of file lcd16x2.c.
LCD_GPIO_Port_EN
#define LCD_GPIO_Port_EN GPIOB
Definition at line 17 of file lcd16x2.c.
RS
#define RS GPIO_PIN_15
Definition at line 10 of file lcd16x2.c.
Function Documentation
lcd_clear()
void lcd_clear (void)
Limpa o display.
Return values
None
Definition at line 198 of file lcd16x2.c.
References lcd_write_command().
Referenced by capsulaInserida(), coolerPID(), heaterPID(), iniciarPreparo(), and relogio().
lcd_init()
void lcd_init (void)
Inicia o display.
Return values
None
Definition at line 163 of file lcd16x2.c.
References HAL_Delay(), lcd_write_command(), and lcd_write_command_init().
lcd_set_cursor()
void lcd_set_cursor (char row, char col)
Posiciona o cursor do display.
Parameters
row linha
col coluna
Return values
None
Definition at line 126 of file lcd16x2.c.
References lcd_write_command().
Referenced by capsulaInserida(), coolerPID(), heaterPID(), iniciarPreparo(), and relogio().
lcd_write_command()
void lcd_write_command (char cmd)
Envia um camando para o display.
Parameters
data Comando a ser enviado
Return values
None
Definition at line 93 of file lcd16x2.c.
References D4, D5, D6, D7, EN, HAL_Delay(), HAL_GPIO_WritePin(), LCD_GPIO_Port, LCD_GPIO_Port_EN, and RS.
Referenced by lcd_clear(), lcd_init(), and lcd_set_cursor().
lcd_write_command_init()
void lcd_write_command_init (char cmd)
Funcao usada para inicializar o display.
Parameters
cmd comando
Return values
None
Definition at line 146 of file lcd16x2.c.
References D4, D5, D6, D7, EN, HAL_GPIO_WritePin(), LCD_GPIO_Port, and LCD_GPIO_Port_EN.
Referenced by lcd_init().
lcd_write_data()
void lcd_write_data (char data)
Escreve um caracter no display.
Parameters
data caracter a ser mostrado
Return values
None
Definition at line 30 of file lcd16x2.c.
References D4, D5, D6, D7, EN, HAL_Delay(), HAL_GPIO_WritePin(), LCD_GPIO_Port, LCD_GPIO_Port_EN, and RS.
Referenced by lcd_write_int(), and lcd_write_string().
lcd_write_int()
void lcd_write_int (int data)
Mostra no display uma variavel do tipo inteiro.
Parameters
data variavel do tipo inteiro a ser enviada
Return values
None
Definition at line 61 of file lcd16x2.c.
References EN, HAL_GPIO_WritePin(), LCD_GPIO_Port, LCD_GPIO_Port_EN, lcd_write_data(), and RS.
lcd_write_string()
void lcd_write_string (char * str)
Escreve uma String no display.
Parameters
str string
Return values
None
Definition at line 207 of file lcd16x2.c.
References lcd_write_data().
Referenced by capsulaInserida(), coolerPID(), heaterPID(), iniciarPreparo(), and relogio().
Variable Documentation
character1
uint8_t character1[8] = { 0x02, 0x04, 0x0E, 0x01, 0x0F, 0x11, 0x0F, 0x00 }
Definition at line 19 of file lcd16x2.c.
character2
uint8_t character2[8] = { 0x02, 0x04, 0x0E, 0x11, 0x1F, 0x10, 0x0E, 0x00 }
Definition at line 20 of file lcd16x2.c.
character3
uint8_t character3[8] = { 0x00, 0x0E, 0x10, 0x10, 0x11, 0x0E, 0x04, 0x00 }
Definition at line 21 of file lcd16x2.c.
character4
uint8_t character4[8] = { 0x1F, 0x00, 0x0E, 0x01, 0x0F, 0x11, 0x0F, 0x00 }
Definition at line 22 of file lcd16x2.c.
character5
uint8_t character5[8] = { 0x1F, 0x00, 0x0E, 0x11, 0x11, 0x11, 0x0E, 0x00 }
Definition at line 23 of file lcd16x2.c.