Final_Project: Core/Inc/lcd16x2.h File Reference
lcd16x2.h File Reference
#include "stm32f1xx_hal.h"
Functions
void lcd_init (void)
Inicia o display.
void lcd_write_data (char data)
Escreve um caracter no display.
void lcd_write_int (int data)
Mostra no display uma variavel do tipo inteiro.
void lcd_write_command (char data)
Envia um camando para o display.
void lcd_custom_char (char loc, char *msg)
void lcd_set_cursor (char lin, char col)
Posiciona o cursor do display.
void lcd_clear (void)
Limpa o display.
void lcd_write_string (char *str)
Escreve uma String no display.
Function Documentation
lcd_clear()
void lcd_clear (void)
Limpa o display.
Return values
None
Definition at line 198 of file lcd16x2.c.
References lcd_write_command().
Referenced by capsulaInserida(), coolerPID(), heaterPID(), iniciarPreparo(), and relogio().
lcd_custom_char()
void lcd_custom_char (char loc, char * msg)
lcd_init()
void lcd_init (void)
Inicia o display.
Return values
None
Definition at line 163 of file lcd16x2.c.
References HAL_Delay(), lcd_write_command(), and lcd_write_command_init().
lcd_set_cursor()
void lcd_set_cursor (char row, char col)
Posiciona o cursor do display.
Parameters
row linha
col coluna
Return values
None
Definition at line 126 of file lcd16x2.c.
References lcd_write_command().
Referenced by capsulaInserida(), coolerPID(), heaterPID(), iniciarPreparo(), and relogio().
lcd_write_command()
void lcd_write_command (char cmd)
Envia um camando para o display.
Parameters
data Comando a ser enviado
Return values
None
Definition at line 93 of file lcd16x2.c.
References D4, D5, D6, D7, EN, HAL_Delay(), HAL_GPIO_WritePin(), LCD_GPIO_Port, LCD_GPIO_Port_EN, and RS.
Referenced by lcd_clear(), lcd_init(), and lcd_set_cursor().
lcd_write_data()
void lcd_write_data (char data)
Escreve um caracter no display.
Parameters
data caracter a ser mostrado
Return values
None
Definition at line 30 of file lcd16x2.c.
References D4, D5, D6, D7, EN, HAL_Delay(), HAL_GPIO_WritePin(), LCD_GPIO_Port, LCD_GPIO_Port_EN, and RS.
Referenced by lcd_write_int(), and lcd_write_string().
lcd_write_int()
void lcd_write_int (int data)
Mostra no display uma variavel do tipo inteiro.
Parameters
data variavel do tipo inteiro a ser enviada
Return values
None
Definition at line 61 of file lcd16x2.c.
References EN, HAL_GPIO_WritePin(), LCD_GPIO_Port, LCD_GPIO_Port_EN, lcd_write_data(), and RS.
lcd_write_string()
void lcd_write_string (char * str)
Escreve uma String no display.
Parameters
str string
Return values
None
Definition at line 207 of file lcd16x2.c.
References lcd_write_data().
Referenced by capsulaInserida(), coolerPID(), heaterPID(), iniciarPreparo(), and relogio().