Final_Project: Core/Src/main.c File Reference
main.c File Reference
: Main program body
#include "main.h"
#include <stdio.h>
#include "lcd16x2.h"
#include "teclado.h"
#include "relogio.h"
#include "capsulas.h"
#include "heartBeat.h"
#include "PWM.h"
Macros
#define TELA_RELOGIO 0
#define TELA_CAPSULA 1
#define ADC_SCALE (3.3 / 4095)
#define NUMBER_OF_CONVERSION 2
#define NUMBER_OF_SAMPLES 32
Functions
void heaterPID (int setPoint)
Controlador PID de aquecimento.
void coolerPID (int setPoint)
Controlador PID de resfriamento.
void SystemClock_Config (void)
System Clock Configuration.
int main (void)
The application entry point.
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef *hadc)
void Error_Handler (void)
This function is executed in case of error occurrence.
Variables
ADC_HandleTypeDef hadc1
DMA_HandleTypeDef hdma_adc1
TIM_HandleTypeDef htim2
int tela = 0
long long previousTimeHeater = 0
long long previousTimeCooler = 0
uint8_t adcDataReady
uint32_t adcData [NUMBER_OF_CONVERSION]
uint32_t adcAvgData = 0
uint32_t adcAvgDataT2 = 0
float T1
float T2
uint32_t contAmostras = 0
Detailed Description
: Main program body
Attention
© Copyright (c) 2020 STMicroelectronics. All rights reserved.
This software component is licensed by ST under BSD 3-Clause license, the "License"; You may not use this file except in compliance with the License. You may obtain a copy of the License at: opensource.org/licenses/BSD-3-Clause
Definition in file main.c.
Macro Definition Documentation
ADC_SCALE
#define ADC_SCALE (3.3 / 4095)
Definition at line 43 of file main.c.
NUMBER_OF_CONVERSION
#define NUMBER_OF_CONVERSION 2
Definition at line 44 of file main.c.
NUMBER_OF_SAMPLES
#define NUMBER_OF_SAMPLES 32
Definition at line 45 of file main.c.
TELA_CAPSULA
#define TELA_CAPSULA 1
Definition at line 42 of file main.c.
TELA_RELOGIO
#define TELA_RELOGIO 0
Definition at line 41 of file main.c.
Function Documentation
coolerPID()
void coolerPID (int setPoint)
Controlador PID de resfriamento.
Return values
Definition at line 538 of file main.c.
References adcAvgData, adcAvgDataT2, adcData, contAmostras, hadc1, HAL_ADC_Start_DMA(), HAL_ADC_Start_IT(), heartBeat(), lcd_clear(), lcd_set_cursor(), lcd_write_string(), NUMBER_OF_CONVERSION, NUMBER_OF_SAMPLES, T1, T2, and TIM2.
Referenced by iniciarPreparo().
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 586 of file main.c.
Referenced by HAL_ADC_MspInit(), and SystemClock_Config().
heaterPID()
void heaterPID (int setPoint)
Controlador PID de aquecimento.
Return values
Definition at line 495 of file main.c.
References adcAvgData, adcAvgDataT2, adcData, contAmostras, hadc1, HAL_ADC_Start_DMA(), HAL_ADC_Start_IT(), heartBeat(), lcd_clear(), lcd_set_cursor(), lcd_write_string(), NUMBER_OF_CONVERSION, NUMBER_OF_SAMPLES, T1, T2, and TIM2.
Referenced by iniciarPreparo().
main()
int main (void)
The application entry point.
Return values
int
Definition at line 94 of file main.c.
References HAL_Init(), and SystemClock_Config().
SystemClock_Config()
void SystemClock_Config (void)
System Clock Configuration.
Return values
None
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
Initializes the CPU, AHB and APB buses clocks
Definition at line 200 of file main.c.
References RCC_PeriphCLKInitTypeDef::AdcClockSelection, RCC_ClkInitTypeDef::AHBCLKDivider, RCC_ClkInitTypeDef::APB1CLKDivider, RCC_ClkInitTypeDef::APB2CLKDivider, RCC_ClkInitTypeDef::ClockType, Error_Handler(), HAL_OK, HAL_RCC_ClockConfig(), HAL_RCC_OscConfig(), HAL_RCCEx_PeriphCLKConfig(), RCC_OscInitTypeDef::HSEPredivValue, RCC_OscInitTypeDef::HSEState, RCC_OscInitTypeDef::HSIState, RCC_OscInitTypeDef::OscillatorType, RCC_PeriphCLKInitTypeDef::PeriphClockSelection, RCC_OscInitTypeDef::PLL, RCC_PLLInitTypeDef::PLLMUL, RCC_PLLInitTypeDef::PLLSource, RCC_PLLInitTypeDef::PLLState, RCC_ADCPCLK2_DIV6, RCC_CLOCKTYPE_HCLK, RCC_CLOCKTYPE_PCLK1, RCC_CLOCKTYPE_PCLK2, RCC_CLOCKTYPE_SYSCLK, RCC_HCLK_DIV1, RCC_HCLK_DIV2, RCC_HSE_ON, RCC_HSE_PREDIV_DIV1, RCC_HSI_ON, RCC_OSCILLATORTYPE_HSE, RCC_PERIPHCLK_ADC, RCC_PLL_MUL9, RCC_PLL_ON, RCC_PLLSOURCE_HSE, RCC_SYSCLK_DIV1, RCC_SYSCLKSOURCE_PLLCLK, and RCC_ClkInitTypeDef::SYSCLKSource.
Referenced by main().
Variable Documentation
adcAvgData
uint32_t adcAvgData = 0
Definition at line 83 of file main.c.
Referenced by coolerPID(), HAL_ADC_ConvCpltCallback(), and heaterPID().
adcAvgDataT2
uint32_t adcAvgDataT2 = 0
Definition at line 84 of file main.c.
Referenced by coolerPID(), HAL_ADC_ConvCpltCallback(), and heaterPID().
adcData
uint32_t adcData[NUMBER_OF_CONVERSION]
Definition at line 82 of file main.c.
Referenced by coolerPID(), HAL_ADC_ConvCpltCallback(), and heaterPID().
adcDataReady
uint8_t adcDataReady
Definition at line 81 of file main.c.
contAmostras
uint32_t contAmostras = 0
Definition at line 87 of file main.c.
Referenced by coolerPID(), HAL_ADC_ConvCpltCallback(), and heaterPID().
hadc1
ADC_HandleTypeDef hadc1
Definition at line 57 of file main.c.
Referenced by coolerPID(), and heaterPID().
hdma_adc1
DMA_HandleTypeDef hdma_adc1
File Name : stm32f1xx_hal_msp.c Description : This file provides code for the MSP Initialization and de-Initialization codes.
Attention
© Copyright (c) 2020 STMicroelectronics. All rights reserved.
This software component is licensed by ST under BSD 3-Clause license, the "License"; You may not use this file except in compliance with the License. You may obtain a copy of the License at: opensource.org/licenses/BSD-3-Clause
Definition at line 58 of file main.c.
Referenced by DMA1_Channel1_IRQHandler(), and HAL_ADC_MspInit().
htim2
TIM_HandleTypeDef htim2
Definition at line 60 of file main.c.
previousTimeCooler
long long previousTimeCooler = 0
Definition at line 65 of file main.c.
previousTimeHeater
long long previousTimeHeater = 0
Definition at line 64 of file main.c.
T1
float T1
Definition at line 85 of file main.c.
Referenced by coolerPID(), and heaterPID().
T2
float T2
Definition at line 86 of file main.c.
Referenced by coolerPID(), and heaterPID().
tela
int tela = 0
Definition at line 63 of file main.c.