Final_Project: Core/Src/relogio.c File Reference
relogio.c File Reference
#include "relogio.h"
Functions
void relogio (Receita capSelected)
Exibe tela do relogio.
void contarRelogio ()
Incrementa a contagem do relogio a cada 1 segundo;.
Variables
int hor = 0
int min = 0
int seg = 0
int segAnt = -1
Function Documentation
contarRelogio()
void contarRelogio (void)
Incrementa a contagem do relogio a cada 1 segundo;.
Return values
Definition at line 54 of file relogio.c.
References HAL_GetTick().
relogio()
void relogio (Receita capSelected)
Exibe tela do relogio.
Return values
Definition at line 24 of file relogio.c.
References hor, lcd_clear(), lcd_set_cursor(), lcd_write_string(), min, seg, segAnt, SEM_CAPSULA, and Receita::tipoCapsula.
Variable Documentation
hor
int hor = 0
Definition at line 12 of file relogio.c.
Referenced by relogio().
min
int min = 0
Definition at line 13 of file relogio.c.
Referenced by __SSAT(), and relogio().
seg
int seg = 0
Definition at line 14 of file relogio.c.
Referenced by relogio().
segAnt
int segAnt = -1
Definition at line 16 of file relogio.c.
Referenced by relogio().